// import type { Metadata } from 'next';
import ReduxProvider from '@/app/login/redux/ReduxProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

// export const metadata: Metadata = {
//     title: 'ReviewApp',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased main bg-[#E5EBFF] min-h-screen h-full p-4 pt-10 pb-6 `}
            >
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
